services:
  # 1. The Database Service
  db:
    image: postgres:15-alpine  # Official lightweight image
    container_name: notes_db_container
    restart: always
    environment:
      POSTGRES_DB: notes_db       # Creates this DB on startup
      POSTGRES_USER: postgres     # Default user
      POSTGRES_PASSWORD: password # Default password
    ports:
      - "5433:5432"               # Expose to host (so you can connect via IntelliJ/DBeaver)
    volumes:
      - db_data:/var/lib/postgresql/data # Persist data even if container stops

  # 2. The Backend Service
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      # This overrides the 'localhost' default in application.properties
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=user123
    depends_on:
      - db

  # 3. The Frontend Service
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

# Define the volume for the DB
volumes:
  db_data: